// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

#ifndef PROTOBUF_INCLUDED_test_2eproto
#define PROTOBUF_INCLUDED_test_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_test_2eproto 

namespace protobuf_test_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_test_2eproto
namespace ssp {
class Test;
class TestDefaultTypeInternal;
extern TestDefaultTypeInternal _Test_default_instance_;
class TestList;
class TestListDefaultTypeInternal;
extern TestListDefaultTypeInternal _TestList_default_instance_;
class UserInfoBase;
class UserInfoBaseDefaultTypeInternal;
extern UserInfoBaseDefaultTypeInternal _UserInfoBase_default_instance_;
}  // namespace ssp
namespace google {
namespace protobuf {
template<> ::ssp::Test* Arena::CreateMaybeMessage<::ssp::Test>(Arena*);
template<> ::ssp::TestList* Arena::CreateMaybeMessage<::ssp::TestList>(Arena*);
template<> ::ssp::UserInfoBase* Arena::CreateMaybeMessage<::ssp::UserInfoBase>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ssp {

// ===================================================================

class Test : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ssp.Test) */ {
 public:
  Test();
  virtual ~Test();

  Test(const Test& from);

  inline Test& operator=(const Test& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Test(Test&& from) noexcept
    : Test() {
    *this = ::std::move(from);
  }

  inline Test& operator=(Test&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Test& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Test* internal_default_instance() {
    return reinterpret_cast<const Test*>(
               &_Test_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Test* other);
  friend void swap(Test& a, Test& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Test* New() const final {
    return CreateMaybeMessage<Test>(NULL);
  }

  Test* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Test>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Test& from);
  void MergeFrom(const Test& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Test* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string d = 4;
  bool has_d() const;
  void clear_d();
  static const int kDFieldNumber = 4;
  const ::std::string& d() const;
  void set_d(const ::std::string& value);
  #if LANG_CXX11
  void set_d(::std::string&& value);
  #endif
  void set_d(const char* value);
  void set_d(const char* value, size_t size);
  ::std::string* mutable_d();
  ::std::string* release_d();
  void set_allocated_d(::std::string* d);

  // optional int32 a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // optional int32 b = 2;
  bool has_b() const;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // optional int32 c = 3;
  bool has_c() const;
  void clear_c();
  static const int kCFieldNumber = 3;
  ::google::protobuf::int32 c() const;
  void set_c(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ssp.Test)
 private:
  void set_has_a();
  void clear_has_a();
  void set_has_b();
  void clear_has_b();
  void set_has_c();
  void clear_has_c();
  void set_has_d();
  void clear_has_d();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr d_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  ::google::protobuf::int32 c_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TestList : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ssp.TestList) */ {
 public:
  TestList();
  virtual ~TestList();

  TestList(const TestList& from);

  inline TestList& operator=(const TestList& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TestList(TestList&& from) noexcept
    : TestList() {
    *this = ::std::move(from);
  }

  inline TestList& operator=(TestList&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TestList& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestList* internal_default_instance() {
    return reinterpret_cast<const TestList*>(
               &_TestList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TestList* other);
  friend void swap(TestList& a, TestList& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TestList* New() const final {
    return CreateMaybeMessage<TestList>(NULL);
  }

  TestList* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TestList>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TestList& from);
  void MergeFrom(const TestList& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ssp.Test tl = 2;
  int tl_size() const;
  void clear_tl();
  static const int kTlFieldNumber = 2;
  ::ssp::Test* mutable_tl(int index);
  ::google::protobuf::RepeatedPtrField< ::ssp::Test >*
      mutable_tl();
  const ::ssp::Test& tl(int index) const;
  ::ssp::Test* add_tl();
  const ::google::protobuf::RepeatedPtrField< ::ssp::Test >&
      tl() const;

  // optional int32 a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:ssp.TestList)
 private:
  void set_has_a();
  void clear_has_a();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ssp::Test > tl_;
  ::google::protobuf::int32 a_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UserInfoBase : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ssp.UserInfoBase) */ {
 public:
  UserInfoBase();
  virtual ~UserInfoBase();

  UserInfoBase(const UserInfoBase& from);

  inline UserInfoBase& operator=(const UserInfoBase& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UserInfoBase(UserInfoBase&& from) noexcept
    : UserInfoBase() {
    *this = ::std::move(from);
  }

  inline UserInfoBase& operator=(UserInfoBase&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UserInfoBase& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UserInfoBase* internal_default_instance() {
    return reinterpret_cast<const UserInfoBase*>(
               &_UserInfoBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(UserInfoBase* other);
  friend void swap(UserInfoBase& a, UserInfoBase& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UserInfoBase* New() const final {
    return CreateMaybeMessage<UserInfoBase>(NULL);
  }

  UserInfoBase* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<UserInfoBase>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const UserInfoBase& from);
  void MergeFrom(const UserInfoBase& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UserInfoBase* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string user_name = 3;
  bool has_user_name() const;
  void clear_user_name();
  static const int kUserNameFieldNumber = 3;
  const ::std::string& user_name() const;
  void set_user_name(const ::std::string& value);
  #if LANG_CXX11
  void set_user_name(::std::string&& value);
  #endif
  void set_user_name(const char* value);
  void set_user_name(const char* value, size_t size);
  ::std::string* mutable_user_name();
  ::std::string* release_user_name();
  void set_allocated_user_name(::std::string* user_name);

  // optional string password = 4;
  bool has_password() const;
  void clear_password();
  static const int kPasswordFieldNumber = 4;
  const ::std::string& password() const;
  void set_password(const ::std::string& value);
  #if LANG_CXX11
  void set_password(::std::string&& value);
  #endif
  void set_password(const char* value);
  void set_password(const char* value, size_t size);
  ::std::string* mutable_password();
  ::std::string* release_password();
  void set_allocated_password(::std::string* password);

  // optional uint32 ver = 1;
  bool has_ver() const;
  void clear_ver();
  static const int kVerFieldNumber = 1;
  ::google::protobuf::uint32 ver() const;
  void set_ver(::google::protobuf::uint32 value);

  // optional uint32 user_id = 2;
  bool has_user_id() const;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // optional uint32 max_t = 33;
  bool has_max_t() const;
  void clear_max_t();
  static const int kMaxTFieldNumber = 33;
  ::google::protobuf::uint32 max_t() const;
  void set_max_t(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ssp.UserInfoBase)
 private:
  void set_has_ver();
  void clear_has_ver();
  void set_has_user_id();
  void clear_has_user_id();
  void set_has_user_name();
  void clear_has_user_name();
  void set_has_password();
  void clear_has_password();
  void set_has_max_t();
  void clear_has_max_t();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_name_;
  ::google::protobuf::internal::ArenaStringPtr password_;
  ::google::protobuf::uint32 ver_;
  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 max_t_;
  friend struct ::protobuf_test_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Test

// optional int32 a = 1;
inline bool Test::has_a() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Test::set_has_a() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Test::clear_has_a() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Test::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 Test::a() const {
  // @@protoc_insertion_point(field_get:ssp.Test.a)
  return a_;
}
inline void Test::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:ssp.Test.a)
}

// optional int32 b = 2;
inline bool Test::has_b() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Test::set_has_b() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Test::clear_has_b() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Test::clear_b() {
  b_ = 0;
  clear_has_b();
}
inline ::google::protobuf::int32 Test::b() const {
  // @@protoc_insertion_point(field_get:ssp.Test.b)
  return b_;
}
inline void Test::set_b(::google::protobuf::int32 value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:ssp.Test.b)
}

// optional int32 c = 3;
inline bool Test::has_c() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Test::set_has_c() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Test::clear_has_c() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Test::clear_c() {
  c_ = 0;
  clear_has_c();
}
inline ::google::protobuf::int32 Test::c() const {
  // @@protoc_insertion_point(field_get:ssp.Test.c)
  return c_;
}
inline void Test::set_c(::google::protobuf::int32 value) {
  set_has_c();
  c_ = value;
  // @@protoc_insertion_point(field_set:ssp.Test.c)
}

// optional string d = 4;
inline bool Test::has_d() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Test::set_has_d() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Test::clear_has_d() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Test::clear_d() {
  d_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_d();
}
inline const ::std::string& Test::d() const {
  // @@protoc_insertion_point(field_get:ssp.Test.d)
  return d_.GetNoArena();
}
inline void Test::set_d(const ::std::string& value) {
  set_has_d();
  d_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ssp.Test.d)
}
#if LANG_CXX11
inline void Test::set_d(::std::string&& value) {
  set_has_d();
  d_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ssp.Test.d)
}
#endif
inline void Test::set_d(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_d();
  d_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ssp.Test.d)
}
inline void Test::set_d(const char* value, size_t size) {
  set_has_d();
  d_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ssp.Test.d)
}
inline ::std::string* Test::mutable_d() {
  set_has_d();
  // @@protoc_insertion_point(field_mutable:ssp.Test.d)
  return d_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Test::release_d() {
  // @@protoc_insertion_point(field_release:ssp.Test.d)
  if (!has_d()) {
    return NULL;
  }
  clear_has_d();
  return d_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Test::set_allocated_d(::std::string* d) {
  if (d != NULL) {
    set_has_d();
  } else {
    clear_has_d();
  }
  d_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), d);
  // @@protoc_insertion_point(field_set_allocated:ssp.Test.d)
}

// -------------------------------------------------------------------

// TestList

// optional int32 a = 1;
inline bool TestList::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TestList::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TestList::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TestList::clear_a() {
  a_ = 0;
  clear_has_a();
}
inline ::google::protobuf::int32 TestList::a() const {
  // @@protoc_insertion_point(field_get:ssp.TestList.a)
  return a_;
}
inline void TestList::set_a(::google::protobuf::int32 value) {
  set_has_a();
  a_ = value;
  // @@protoc_insertion_point(field_set:ssp.TestList.a)
}

// repeated .ssp.Test tl = 2;
inline int TestList::tl_size() const {
  return tl_.size();
}
inline void TestList::clear_tl() {
  tl_.Clear();
}
inline ::ssp::Test* TestList::mutable_tl(int index) {
  // @@protoc_insertion_point(field_mutable:ssp.TestList.tl)
  return tl_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ssp::Test >*
TestList::mutable_tl() {
  // @@protoc_insertion_point(field_mutable_list:ssp.TestList.tl)
  return &tl_;
}
inline const ::ssp::Test& TestList::tl(int index) const {
  // @@protoc_insertion_point(field_get:ssp.TestList.tl)
  return tl_.Get(index);
}
inline ::ssp::Test* TestList::add_tl() {
  // @@protoc_insertion_point(field_add:ssp.TestList.tl)
  return tl_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ssp::Test >&
TestList::tl() const {
  // @@protoc_insertion_point(field_list:ssp.TestList.tl)
  return tl_;
}

// -------------------------------------------------------------------

// UserInfoBase

// optional uint32 ver = 1;
inline bool UserInfoBase::has_ver() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void UserInfoBase::set_has_ver() {
  _has_bits_[0] |= 0x00000004u;
}
inline void UserInfoBase::clear_has_ver() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void UserInfoBase::clear_ver() {
  ver_ = 0u;
  clear_has_ver();
}
inline ::google::protobuf::uint32 UserInfoBase::ver() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.ver)
  return ver_;
}
inline void UserInfoBase::set_ver(::google::protobuf::uint32 value) {
  set_has_ver();
  ver_ = value;
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.ver)
}

// optional uint32 user_id = 2;
inline bool UserInfoBase::has_user_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void UserInfoBase::set_has_user_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void UserInfoBase::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void UserInfoBase::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 UserInfoBase::user_id() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.user_id)
  return user_id_;
}
inline void UserInfoBase::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.user_id)
}

// optional string user_name = 3;
inline bool UserInfoBase::has_user_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void UserInfoBase::set_has_user_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void UserInfoBase::clear_has_user_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void UserInfoBase::clear_user_name() {
  user_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user_name();
}
inline const ::std::string& UserInfoBase::user_name() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.user_name)
  return user_name_.GetNoArena();
}
inline void UserInfoBase::set_user_name(const ::std::string& value) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.user_name)
}
#if LANG_CXX11
inline void UserInfoBase::set_user_name(::std::string&& value) {
  set_has_user_name();
  user_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ssp.UserInfoBase.user_name)
}
#endif
inline void UserInfoBase::set_user_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ssp.UserInfoBase.user_name)
}
inline void UserInfoBase::set_user_name(const char* value, size_t size) {
  set_has_user_name();
  user_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ssp.UserInfoBase.user_name)
}
inline ::std::string* UserInfoBase::mutable_user_name() {
  set_has_user_name();
  // @@protoc_insertion_point(field_mutable:ssp.UserInfoBase.user_name)
  return user_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserInfoBase::release_user_name() {
  // @@protoc_insertion_point(field_release:ssp.UserInfoBase.user_name)
  if (!has_user_name()) {
    return NULL;
  }
  clear_has_user_name();
  return user_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfoBase::set_allocated_user_name(::std::string* user_name) {
  if (user_name != NULL) {
    set_has_user_name();
  } else {
    clear_has_user_name();
  }
  user_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user_name);
  // @@protoc_insertion_point(field_set_allocated:ssp.UserInfoBase.user_name)
}

// optional string password = 4;
inline bool UserInfoBase::has_password() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void UserInfoBase::set_has_password() {
  _has_bits_[0] |= 0x00000002u;
}
inline void UserInfoBase::clear_has_password() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void UserInfoBase::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_password();
}
inline const ::std::string& UserInfoBase::password() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.password)
  return password_.GetNoArena();
}
inline void UserInfoBase::set_password(const ::std::string& value) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.password)
}
#if LANG_CXX11
inline void UserInfoBase::set_password(::std::string&& value) {
  set_has_password();
  password_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ssp.UserInfoBase.password)
}
#endif
inline void UserInfoBase::set_password(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ssp.UserInfoBase.password)
}
inline void UserInfoBase::set_password(const char* value, size_t size) {
  set_has_password();
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ssp.UserInfoBase.password)
}
inline ::std::string* UserInfoBase::mutable_password() {
  set_has_password();
  // @@protoc_insertion_point(field_mutable:ssp.UserInfoBase.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* UserInfoBase::release_password() {
  // @@protoc_insertion_point(field_release:ssp.UserInfoBase.password)
  if (!has_password()) {
    return NULL;
  }
  clear_has_password();
  return password_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void UserInfoBase::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    set_has_password();
  } else {
    clear_has_password();
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:ssp.UserInfoBase.password)
}

// optional uint32 max_t = 33;
inline bool UserInfoBase::has_max_t() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void UserInfoBase::set_has_max_t() {
  _has_bits_[0] |= 0x00000010u;
}
inline void UserInfoBase::clear_has_max_t() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void UserInfoBase::clear_max_t() {
  max_t_ = 0u;
  clear_has_max_t();
}
inline ::google::protobuf::uint32 UserInfoBase::max_t() const {
  // @@protoc_insertion_point(field_get:ssp.UserInfoBase.max_t)
  return max_t_;
}
inline void UserInfoBase::set_max_t(::google::protobuf::uint32 value) {
  set_has_max_t();
  max_t_ = value;
  // @@protoc_insertion_point(field_set:ssp.UserInfoBase.max_t)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ssp

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_test_2eproto
