// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: relation_info_base.proto

#ifndef PROTOBUF_INCLUDED_relation_5finfo_5fbase_2eproto
#define PROTOBUF_INCLUDED_relation_5finfo_5fbase_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_relation_5finfo_5fbase_2eproto 

namespace protobuf_relation_5finfo_5fbase_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_relation_5finfo_5fbase_2eproto
namespace ssp {
class RelationInfoBase;
class RelationInfoBaseDefaultTypeInternal;
extern RelationInfoBaseDefaultTypeInternal _RelationInfoBase_default_instance_;
}  // namespace ssp
namespace google {
namespace protobuf {
template<> ::ssp::RelationInfoBase* Arena::CreateMaybeMessage<::ssp::RelationInfoBase>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ssp {

// ===================================================================

class RelationInfoBase : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ssp.RelationInfoBase) */ {
 public:
  RelationInfoBase();
  virtual ~RelationInfoBase();

  RelationInfoBase(const RelationInfoBase& from);

  inline RelationInfoBase& operator=(const RelationInfoBase& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RelationInfoBase(RelationInfoBase&& from) noexcept
    : RelationInfoBase() {
    *this = ::std::move(from);
  }

  inline RelationInfoBase& operator=(RelationInfoBase&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RelationInfoBase& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RelationInfoBase* internal_default_instance() {
    return reinterpret_cast<const RelationInfoBase*>(
               &_RelationInfoBase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RelationInfoBase* other);
  friend void swap(RelationInfoBase& a, RelationInfoBase& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RelationInfoBase* New() const final {
    return CreateMaybeMessage<RelationInfoBase>(NULL);
  }

  RelationInfoBase* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RelationInfoBase>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RelationInfoBase& from);
  void MergeFrom(const RelationInfoBase& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RelationInfoBase* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 friend_list = 3;
  int friend_list_size() const;
  void clear_friend_list();
  static const int kFriendListFieldNumber = 3;
  ::google::protobuf::uint32 friend_list(int index) const;
  void set_friend_list(int index, ::google::protobuf::uint32 value);
  void add_friend_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      friend_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_friend_list();

  // repeated uint32 black_list = 4;
  int black_list_size() const;
  void clear_black_list();
  static const int kBlackListFieldNumber = 4;
  ::google::protobuf::uint32 black_list(int index) const;
  void set_black_list(int index, ::google::protobuf::uint32 value);
  void add_black_list(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      black_list() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_black_list();

  // optional uint32 ver = 1;
  bool has_ver() const;
  void clear_ver();
  static const int kVerFieldNumber = 1;
  ::google::protobuf::uint32 ver() const;
  void set_ver(::google::protobuf::uint32 value);

  // optional uint32 user_id = 2;
  bool has_user_id() const;
  void clear_user_id();
  static const int kUserIdFieldNumber = 2;
  ::google::protobuf::uint32 user_id() const;
  void set_user_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ssp.RelationInfoBase)
 private:
  void set_has_ver();
  void clear_has_ver();
  void set_has_user_id();
  void clear_has_user_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > friend_list_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > black_list_;
  ::google::protobuf::uint32 ver_;
  ::google::protobuf::uint32 user_id_;
  friend struct ::protobuf_relation_5finfo_5fbase_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RelationInfoBase

// optional uint32 ver = 1;
inline bool RelationInfoBase::has_ver() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RelationInfoBase::set_has_ver() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RelationInfoBase::clear_has_ver() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RelationInfoBase::clear_ver() {
  ver_ = 0u;
  clear_has_ver();
}
inline ::google::protobuf::uint32 RelationInfoBase::ver() const {
  // @@protoc_insertion_point(field_get:ssp.RelationInfoBase.ver)
  return ver_;
}
inline void RelationInfoBase::set_ver(::google::protobuf::uint32 value) {
  set_has_ver();
  ver_ = value;
  // @@protoc_insertion_point(field_set:ssp.RelationInfoBase.ver)
}

// optional uint32 user_id = 2;
inline bool RelationInfoBase::has_user_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RelationInfoBase::set_has_user_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RelationInfoBase::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RelationInfoBase::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 RelationInfoBase::user_id() const {
  // @@protoc_insertion_point(field_get:ssp.RelationInfoBase.user_id)
  return user_id_;
}
inline void RelationInfoBase::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
  // @@protoc_insertion_point(field_set:ssp.RelationInfoBase.user_id)
}

// repeated uint32 friend_list = 3;
inline int RelationInfoBase::friend_list_size() const {
  return friend_list_.size();
}
inline void RelationInfoBase::clear_friend_list() {
  friend_list_.Clear();
}
inline ::google::protobuf::uint32 RelationInfoBase::friend_list(int index) const {
  // @@protoc_insertion_point(field_get:ssp.RelationInfoBase.friend_list)
  return friend_list_.Get(index);
}
inline void RelationInfoBase::set_friend_list(int index, ::google::protobuf::uint32 value) {
  friend_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:ssp.RelationInfoBase.friend_list)
}
inline void RelationInfoBase::add_friend_list(::google::protobuf::uint32 value) {
  friend_list_.Add(value);
  // @@protoc_insertion_point(field_add:ssp.RelationInfoBase.friend_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
RelationInfoBase::friend_list() const {
  // @@protoc_insertion_point(field_list:ssp.RelationInfoBase.friend_list)
  return friend_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
RelationInfoBase::mutable_friend_list() {
  // @@protoc_insertion_point(field_mutable_list:ssp.RelationInfoBase.friend_list)
  return &friend_list_;
}

// repeated uint32 black_list = 4;
inline int RelationInfoBase::black_list_size() const {
  return black_list_.size();
}
inline void RelationInfoBase::clear_black_list() {
  black_list_.Clear();
}
inline ::google::protobuf::uint32 RelationInfoBase::black_list(int index) const {
  // @@protoc_insertion_point(field_get:ssp.RelationInfoBase.black_list)
  return black_list_.Get(index);
}
inline void RelationInfoBase::set_black_list(int index, ::google::protobuf::uint32 value) {
  black_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:ssp.RelationInfoBase.black_list)
}
inline void RelationInfoBase::add_black_list(::google::protobuf::uint32 value) {
  black_list_.Add(value);
  // @@protoc_insertion_point(field_add:ssp.RelationInfoBase.black_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
RelationInfoBase::black_list() const {
  // @@protoc_insertion_point(field_list:ssp.RelationInfoBase.black_list)
  return black_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
RelationInfoBase::mutable_black_list() {
  // @@protoc_insertion_point(field_mutable_list:ssp.RelationInfoBase.black_list)
  return &black_list_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ssp

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_relation_5finfo_5fbase_2eproto
